#if	!defined(DT_CHAR)

/*	Data types, formats, access are enumerated, code should use them way. */
/*	But hsctype.idl needs them as constants. */
/*	So they a wrapped in NOT_USING_DICTIONARY_ENUM */

#if defined(NOT_USING_DICTIONARY_ENUM)


/*	Data types */

#define	DT_CHAR	1
#define	DT_INT2	2
#define	DT_INT4	3
#define	DT_REAL	4
#define	DT_DBLE	5
#define	DT_HIST	6
#define	DT_VAR	7
#define	DT_ENUM	8
#define	DT_DATE_TIME	9
#define	DT_STATUS	10
#define	DT_SRCADDR	11
#define	DT_DSTADDR	12
#define	DT_SERVAR	13
#define	DT_POINTREF	14
#define	DT_INT8	15
#define	DT_TIME	16
#define	DT_DELTATIME	17
#define	DT_TIMEOFDAY	18
#define	DT_ALARMHANDLE	19
#define	DT_POINTREF2	20

/*	Data formats */

#define	DF_CHAR	1
#define	DF_NUM	2
#define	DF_POINT	3
#define	DF_PARAM	4
#define	DF_ENG	5
#define	DF_PCT	6
#define	DF_ENUM	7
#define	DF_MODE	8
#define	DF_BIT	9
#define	DF_STATE	10
#define	DF_PNTTYPE	11
#define	DF_TIME	12
#define	DF_DATE	13
#define	DF_DATE_TIME	14
#define	DF_GETVAL	15
#define	DF_DATE_TIME_UST	16
#define	DF_ENUM_SET	17

/*	Data access methods */

#define	DA_DATAIO	1
#define	DA_PRMDEF	2
#define	DA_PARAM	3
#define	DA_CDA	4
#define	DA_EVENT	5
#define	DA_QUE	6
#define	DA_HISTORY	7
#define	DA_CONSTANT	8
#define	DA_HIST_DTM	9
#define	DA_VARIABLE	10
#define	DA_POINT	11
#define	DA_FIELDBUS_MODE	12
#define	DA_ALMCOUNT	13
#define	DA_MSGCOUNT	14
#define	DA_PNTALM	15
#define	DA_RELATIVES	16
#define	DA_PNTBLK	17
#define	DA_FUNCTION	18
#define	DA_ALTCOUNT	19
#define	DA_UNRESOLVED	20
#define	DA_SCANNED	21
#define	DA_ALARMED	22


#endif



/*	Point types */

#define	STA	1
#define	ANA	2
#define	ACC	3
#define	ACS	4
#define	CON	5
#define	ASH	6
#define	CLH	7
#define	SYS	8
#define	ORH	9
#define	ONT	10
#define	CDA	101
#define	RDA	102
#define	PSA	103
#define	ACT	104

/*	Point subtypes */

#define	CLH_PROCESS	1001
#define	CLH_SYSTEM	1002
#define	SYS_MODEL	1001
#define	SYS_SERVER	1002
#define	SYS_CONTROLLERS	1003
#define	SYS_CHANNEL	1004
#define	SYS_CONTROLLER	1005
#define	SYS_PRINTERS	1006
#define	SYS_PRINTER	1007
#define	SYS_SYSINTERFACES	1008
#define	SYS_SYSINTERFACE	1009
#define	SYS_STATIONS	1010
#define	SYS_FLEXSTATIONS	1011
#define	SYS_CONSSTATIONS	1012
#define	SYS_FLEXSTATION	1013
#define	SYS_CONSSTATION	1014
#define	SYS_CONSOLES	1015
#define	SYS_CONSOLE	1016
#define	SYS_CSTNCLIENT	1017
#define	SYS_UNASSIGNEDITEMS	1018
#define	SYS_COMPUTERS	1019
#define	SYS_COMPUTER	1020
#define	SYS_DOMAIN	1021
#define	SYS_ORGUNIT	1022
#define	SYS_NETEQUIP	1023
#define	SYS_SWITCH	1024
#define	SYS_FTE	1025
#define	SYS_FTECOMMUNITY	1026
#define	SYS_FTEDEVICE	1027
#define	SYS_9PSWITCH	1028
#define	SYS_UNKNOWNCONTROLLERS	1029
#define	SYS_PNTSRV_CONTROLLER	1030
#define	SYS_PNTSRV_CHANNEL	1031
#define	SYS_PNTSRV_NETWORK	1032
#define	SYS_ORPHANACTS	1033
#define	SYS_METER	1034
#define	SYS_APPLICATIONS	1035
#define	SYS_APPLICATION	1036
#define	SYS_PNTSRV_SYSTEM_HIDDEN	1037
#define	SYS_CONTROLLER_WIRELESS	1038
#define	SYS_NBCCS	1039
#define	SYS_NBCC	1040
#define	SYS_CONTROLLER_IORACK	1041

/*	Point parameters */

#define	param_PV	1
#define	PV	1
#define	param_MD	2
#define	MD	2
#define	param_OP	3
#define	OP	3
#define	param_SP	4
#define	SP	4
#define	param_A1	5
#define	A1	5
#define	param_A2	6
#define	A2	6
#define	param_A3	7
#define	A3	7
#define	param_A4	8
#define	A4	8
#define	param_EULO	16
#define	EULO	16
#define	param_EUHI	17
#define	EUHI	17
#define	param_NumberOfParents	30
#define	param_ACODE	31
#define	ACODE	31
#define	param_NAME	36
#define	NAME	36
#define	param_DESC	37
#define	DESC	37
#define	param_PVDAY	38
#define	PVDAY	38
#define	param_PVSEC	39
#define	PVSEC	39
#define	param_HBASE	40
#define	HBASE	40
#define	param_H1M	41
#define	H1M	41
#define	param_H6M	42
#define	H6M	42
#define	param_H1H	43
#define	H1H	43
#define	param_H8H	44
#define	H8H	44
#define	param_H24H	45
#define	H24H	45
#define	param_H5SF	46
#define	H5SF	46
#define	param_H1HE	47
#define	H1HE	47
#define	param_H8HE	48
#define	H8HE	48
#define	param_H24HE	49
#define	H24HE	49
#define	param_SCNSTS	56
#define	SCNSTS	56
#define	param_ALMSTS	57
#define	ALMSTS	57
#define	param_CNTLEV	58
#define	CNTLEV	58
#define	param_ALMINH	59
#define	ALMINH	59
#define	param_PVEROR	60
#define	PVEROR	60
#define	param_MDEROR	61
#define	MDEROR	61
#define	param_OPEROR	62
#define	OPEROR	62
#define	param_SPEROR	63
#define	SPEROR	63
#define	param_A1EROR	64
#define	A1EROR	64
#define	param_A2EROR	65
#define	A2EROR	65
#define	param_A3EROR	66
#define	A3EROR	66
#define	param_A4EROR	67
#define	A4EROR	67
#define	param_UNITS	68
#define	UNITS	68
#define	param_UNITS1	69
#define	UNITS1	69
#define	param_UNITS2	70
#define	UNITS2	70
#define	param_UNITS3	71
#define	UNITS3	71
#define	param_UNITS4	72
#define	UNITS4	72
#define	param_UNITS5	73
#define	UNITS5	73
#define	param_UNITS6	74
#define	UNITS6	74
#define	param_UNITS7	75
#define	UNITS7	75
#define	param_TARGET0	76
#define	TARGET0	76
#define	param_TARGET1	77
#define	TARGET1	77
#define	param_TARGET2	78
#define	TARGET2	78
#define	param_TARGET3	79
#define	TARGET3	79
#define	param_ENTZNE	80
#define	ENTZNE	80
#define	param_PVALG	85
#define	PVALG	85
#define	param_PVBLK	86
#define	PVBLK	86
#define	param_ACALG	87
#define	ACALG	87
#define	param_ACBLK	88
#define	ACBLK	88
#define	param_UNACKN	89
#define	UNACKN	89
#define	param_CNTPRI	91
#define	CNTPRI	91
#define	param_AL1PRI	92
#define	AL1PRI	92
#define	param_AL2PRI	93
#define	AL2PRI	93
#define	param_AL3PRI	94
#define	AL3PRI	94
#define	param_AL4PRI	95
#define	AL4PRI	95
#define	param_AL5PRI	96
#define	AL5PRI	96
#define	param_AL6PRI	97
#define	AL6PRI	97
#define	param_AL7PRI	98
#define	AL7PRI	98
#define	param_AL8PRI	99
#define	AL8PRI	99
#define	param_ALMSUB	100
#define	ALMSUB	100
#define	param_CNTSUB	101
#define	CNTSUB	101
#define	param_AL1SUB	102
#define	AL1SUB	102
#define	param_AL2SUB	103
#define	AL2SUB	103
#define	param_AL3SUB	104
#define	AL3SUB	104
#define	param_AL4SUB	105
#define	AL4SUB	105
#define	param_AL5SUB	106
#define	AL5SUB	106
#define	param_AL6SUB	107
#define	AL6SUB	107
#define	param_AL7SUB	108
#define	AL7SUB	108
#define	param_AL8SUB	109
#define	AL8SUB	109
#define	param_AssociatedTrend	110
#define	param_MAPALM	113
#define	param_ALRMSG	114
#define	param_REALARM	116
#define	param_EXTPVCHANGE	117
#define	param_EXTMDCHANGE	118
#define	param_EXTOPCHANGE	119
#define	param_EXTSPCHANGE	120
#define	param_AL1ARMED	121
#define	param_AL2ARMED	122
#define	param_AL3ARMED	123
#define	param_AL4ARMED	124
#define	param_AL5ARMED	125
#define	param_AL6ARMED	126
#define	param_AL7ARMED	127
#define	param_AL8ARMED	128
#define	param_IPWIDTH	129
#define	param_OPWIDTH	130
#define	param_NORMALMODE	131
#define	param_PULSEWIDTH	132
#define	param_CTRLCONFIRM	134
#define	param_CTRLTIMEOUT	135
#define	param_PvSource	140
#define	param_MdSource	141
#define	param_OpSource	142
#define	param_SpSource	143
#define	param_A1Source	144
#define	param_A2Source	145
#define	param_A3Source	146
#define	param_A4Source	147
#define	param_AckDestination	148
#define	param_MdDestination	149
#define	param_OpDestination	150
#define	param_SpDestination	151
#define	param_A1Destination	152
#define	param_A2Destination	153
#define	param_A3Destination	154
#define	param_A4Destination	155
#define	param_PvPeriod	156
#define	param_MdPeriod	157
#define	param_OpPeriod	158
#define	param_SpPeriod	159
#define	param_A1Period	160
#define	param_A2Period	161
#define	param_A3Period	162
#define	param_A4Period	163
#define	param_PvController	164
#define	param_MdController	165
#define	param_OpController	166
#define	param_SpController	167
#define	param_A1Controller	168
#define	param_A2Controller	169
#define	param_A3Controller	170
#define	param_A4Controller	171
#define	param_CreateTime	172
#define	param_AlarmPriority	181
#define	param_AlarmSubPriority	182
#define	param_SrvConNum	183
#define	param_SrvConLinkNum	184
#define	param_ItemName	185
#define	param_FullItemName	186
#define	param_DefaultName	187
#define	param_LocationFullItemName	188
#define	param_LocationTagName	189
#define	param_PointDetailDisplayDefault	200
#define	param_GroupDetailDisplayDefault	201
#define	param_Assignable	211
#define	param_OwnerTagName	212
#define	param_DisablePVAlarmJounaling	213
#define	param_Guid	234
#define	param_AssociatedDisplay	237
#define	param_InstructionDisplay	238
#define	param_PVstatus	249
#define	param_MDstatus	250
#define	param_OPstatus	251
#define	param_SPstatus	252
#define	param_A1status	253
#define	param_A2status	254
#define	param_A3status	255
#define	param_A4status	256
#define	param_InState0	257
#define	param_InState1	258
#define	param_InState2	259
#define	param_InState3	260
#define	param_InState4	261
#define	param_InState5	262
#define	param_InState6	263
#define	param_InState7	264
#define	param_PV_Bit0	265
#define	param_PV_Bit1	266
#define	param_PV_Bit2	267
#define	param_OP_Bit0	269
#define	param_OP_Bit1	270
#define	param_PVREVERSE	277
#define	param_MDREVERSE	278
#define	param_OPREVERSE	279
#define	param_SPREVERSE	280
#define	param_A1REVERSE	281
#define	param_A2REVERSE	282
#define	param_A3REVERSE	283
#define	param_A4REVERSE	284
#define	param_OwnerItemName	285
#define	param_LocalPointType	286
#define	param_PointType	291
#define	param_PointSubType	292
#define	param_JournalOnly	293
#define	param_ManualPV	294
#define	param_ControlInhibit	295
#define	param_FieldPVstatus	300
#define	param_FieldPV	301
#define	param_FieldPVquality	302
#define	param_INALM	303
#define	param_INALARM0	304
#define	param_INALARM1	305
#define	param_INALARM2	306
#define	param_INALARM3	307
#define	param_INALARM4	308
#define	param_INALARM5	309
#define	param_INALARM6	310
#define	param_INALARM7	311
#define	param_EXTA1CHANGE	315
#define	param_EXTA2CHANGE	316
#define	param_EXTA3CHANGE	317
#define	param_EXTA4CHANGE	318
#define	param_MDDISABL	319
#define	param_A1ASSOCP	320
#define	param_A2ASSOCP	321
#define	param_A3ASSOCP	322
#define	param_A4ASSOCP	323
#define	param_TotalCriticalRTNUnackAlarms	826
#define	param_TotalCriticalActiveUnackAlarms	827
#define	param_TotalCriticalActiveAckAlarms	828
#define	param_TotalCriticalRTNAckAlarms	829
#define	param_TotalCriticalRTNAlarms	830
#define	param_TotalCriticalUnackAlarms	831
#define	param_TotalCriticalActiveAlarms	832
#define	param_TotalCriticalAckAlarms	833
#define	param_TotalCriticalAlarms	834
#define	param_TotalUrgentRTNUnackAlarms	326
#define	param_TotalUrgentActiveUnackAlarms	327
#define	param_TotalUrgentActiveAckAlarms	328
#define	param_TotalUrgentRTNAckAlarms	329
#define	param_TotalUrgentRTNAlarms	330
#define	param_TotalUrgentUnackAlarms	331
#define	param_TotalUrgentActiveAlarms	332
#define	param_TotalUrgentAckAlarms	333
#define	param_TotalUrgentAlarms	334
#define	param_TotalHighRTNUnackAlarms	335
#define	param_TotalHighActiveUnackAlarms	336
#define	param_TotalHighActiveAckAlarms	337
#define	param_TotalHighRTNAckAlarms	338
#define	param_TotalHighRTNAlarms	339
#define	param_TotalHighUnackAlarms	340
#define	param_TotalHighActiveAlarms	341
#define	param_TotalHighAckAlarms	342
#define	param_TotalHighAlarms	343
#define	param_TotalLowRTNUnackAlarms	344
#define	param_TotalLowActiveUnackAlarms	345
#define	param_TotalLowActiveAckAlarms	346
#define	param_TotalLowRTNAckAlarms	347
#define	param_TotalLowRTNAlarms	348
#define	param_TotalLowUnackAlarms	349
#define	param_TotalLowActiveAlarms	350
#define	param_TotalLowAckAlarms	351
#define	param_TotalLowAlarms	352
#define	param_TotalRTNUnackAlarms	353
#define	param_TotalActiveUnackAlarms	354
#define	param_TotalActiveAckAlarms	355
#define	param_TotalRTNAckAlarms	356
#define	param_TotalRTNAlarms	357
#define	param_TotalUnackAlarms	358
#define	param_TotalActiveAlarms	359
#define	param_TotalAckAlarms	360
#define	param_TotalAlarms	361
#define	param_TotalUnackInfoMessages	362
#define	param_TotalUnackConfMessages	363
#define	param_TotalAckConfMessages	364
#define	param_TotalAckInfoMessages	365
#define	param_TotalAckConfConfMessages	482
#define	param_TotalInfoMessages	366
#define	param_TotalUnackMessages	367
#define	param_TotalConfMessages	368
#define	param_TotalAckMessages	369
#define	param_TotalMessages	370
#define	param_Parents	371
#define	param_Children	372
#define	param_TotalDisabledAlarms	373
#define	param_TotalDisabledAlerts	374
#define	param_TotalRTNAlerts	375
#define	param_TotalRTNUnackAlerts	376
#define	param_TotalRTNAckAlerts	377
#define	param_TotalActiveAlerts	378
#define	param_TotalActiveUnackAlerts	379
#define	param_TotalActiveAckAlerts	380
#define	param_TotalAckAlerts	381
#define	param_TotalUnackAlerts	382
#define	param_TotalAlerts	383
#define	param_ItemNumber	432
#define	param_SIGINH	462
#define	param_TotalShelvedAlarms	466
#define	param_TotalShelvedAlerts	467
#define	param_TotalSuppressedAlarms	485
#define	param_AcmSrvNum	487
#define	param_AcmSysNum	488
#define	param_PVISCOMPOSITE	497
#define	param_MDISCOMPOSITE	498
#define	param_OPISCOMPOSITE	499
#define	param_PVREVERSEMASK	600
#define	param_MDREVERSEMASK	601
#define	param_OPREVERSEMASK	602
#define	param_PVREVERSEBIT0	603
#define	param_PVREVERSEBIT1	604
#define	param_PVREVERSEBIT2	605
#define	param_PVREVERSEBIT3	606
#define	param_MDREVERSEBIT0	607
#define	param_MDREVERSEBIT1	608
#define	param_MDREVERSEBIT2	609
#define	param_MDREVERSEBIT3	610
#define	param_OPREVERSEBIT0	611
#define	param_OPREVERSEBIT1	612
#define	param_OPREVERSEBIT2	613
#define	param_OPREVERSEBIT3	614
#define	param_GenAlmOnDelay	615
#define	param_State0OnDelay	616
#define	param_State1OnDelay	617
#define	param_State2OnDelay	618
#define	param_State3OnDelay	619
#define	param_State4OnDelay	620
#define	param_State5OnDelay	621
#define	param_State6OnDelay	622
#define	param_State7OnDelay	623
#define	param_GenAlmOffDelay	624
#define	param_State0OffDelay	625
#define	param_State1OffDelay	626
#define	param_State2OffDelay	627
#define	param_State3OffDelay	628
#define	param_State4OffDelay	629
#define	param_State5OffDelay	630
#define	param_State6OffDelay	631
#define	param_State7OffDelay	632
#define	param_InGenAlmOnDelay	633
#define	param_InState0OnDelay	634
#define	param_InState1OnDelay	635
#define	param_InState2OnDelay	636
#define	param_InState3OnDelay	637
#define	param_InState4OnDelay	638
#define	param_InState5OnDelay	639
#define	param_InState6OnDelay	640
#define	param_InState7OnDelay	641
#define	param_InGenAlmOffDelay	642
#define	param_InState0OffDelay	643
#define	param_InState1OffDelay	644
#define	param_InState2OffDelay	645
#define	param_InState3OffDelay	646
#define	param_InState4OffDelay	647
#define	param_InState5OffDelay	648
#define	param_InState6OffDelay	649
#define	param_InState7OffDelay	650
#define	param_PVQUALITY	651
#define	param_MDQUALITY	652
#define	param_OPQUALITY	653
#define	param_SPQUALITY	654
#define	param_A1QUALITY	655
#define	param_A2QUALITY	656
#define	param_A3QUALITY	657
#define	param_A4QUALITY	658
#define	param_PVLastScannedTime	659
#define	param_MDLastScannedTime	660
#define	param_OPLastScannedTime	661
#define	param_SPLastScannedTime	662
#define	param_A1LastScannedTime	663
#define	param_A2LastScannedTime	664
#define	param_A3LastScannedTime	665
#define	param_A4LastScannedTime	666
#define	param_PVDynamicScanningDisabled	733
#define	param_MDDynamicScanningDisabled	734
#define	param_OPDynamicScanningDisabled	735
#define	param_SPDynamicScanningDisabled	736
#define	param_A1DynamicScanningDisabled	737
#define	param_A2DynamicScanningDisabled	738
#define	param_A3DynamicScanningDisabled	739
#define	param_A4DynamicScanningDisabled	740
#define	param_AlarmFlags	852
#define	param_AL1	18
#define	AL1	18
#define	param_AL2	19
#define	AL2	19
#define	param_AL3	20
#define	AL3	20
#define	param_AL4	21
#define	AL4	21
#define	param_AT1	22
#define	AT1	22
#define	param_AT2	23
#define	AT2	23
#define	param_AT3	24
#define	AT3	24
#define	param_AT4	25
#define	AT4	25
#define	param_SPLO	32
#define	SPLO	32
#define	param_SPHI	33
#define	SPHI	33
#define	param_OPLO	34
#define	OPLO	34
#define	param_OPHI	35
#define	OPHI	35
#define	param_ALMPRI	90
#define	ALMPRI	90
#define	param_DFTDEADBAND	136
#define	param_ALMDEADBAND	137
#define	param_CNTDEADBAND	138
#define	param_PVCLAMP	139
#define	param_AL5	173
#define	AL5	173
#define	param_AL6	174
#define	AL6	174
#define	param_AL7	175
#define	AL7	175
#define	param_AL8	176
#define	AL8	176
#define	param_AT5	177
#define	AT5	177
#define	param_AT6	178
#define	AT6	178
#define	param_AT7	179
#define	AT7	179
#define	param_AT8	180
#define	AT8	180
#define	param_BiasScaleEnable	287
#define	param_Bias	288
#define	param_Scale	289
#define	param_USRALM1	296
#define	param_USRALM2	297
#define	param_USRALM3	298
#define	param_USRALM4	299
#define	param_RATEALM	304
#define	param_DVLOALM	305
#define	param_DVHIALM	306
#define	param_XTLOALM	307
#define	param_XTHIALM	308
#define	param_PVLOALM	309
#define	param_PVHIALM	310
#define	param_PVLOLOALM	311
#define	param_PVHIHIALM	312
#define	param_RSLOALM	313
#define	param_RSHIALM	314
#define	param_Alarm1OnDelay	616
#define	param_Alarm2OnDelay	617
#define	param_Alarm3OnDelay	618
#define	param_Alarm4OnDelay	619
#define	param_Alarm5OnDelay	620
#define	param_Alarm6OnDelay	621
#define	param_Alarm7OnDelay	622
#define	param_Alarm8OnDelay	623
#define	param_Alarm1OffDelay	625
#define	param_Alarm2OffDelay	626
#define	param_Alarm3OffDelay	627
#define	param_Alarm4OffDelay	628
#define	param_Alarm5OffDelay	629
#define	param_Alarm6OffDelay	630
#define	param_Alarm7OffDelay	631
#define	param_Alarm8OffDelay	632
#define	param_InAlarm1OnDelay	634
#define	param_InAlarm2OnDelay	635
#define	param_InAlarm3OnDelay	636
#define	param_InAlarm4OnDelay	637
#define	param_InAlarm5OnDelay	638
#define	param_InAlarm6OnDelay	639
#define	param_InAlarm7OnDelay	640
#define	param_InAlarm8OnDelay	641
#define	param_InAlarm1OffDelay	643
#define	param_InAlarm2OffDelay	644
#define	param_InAlarm3OffDelay	645
#define	param_InAlarm4OffDelay	646
#define	param_InAlarm5OffDelay	647
#define	param_InAlarm6OffDelay	648
#define	param_InAlarm7OffDelay	649
#define	param_InAlarm8OffDelay	650
#define	param_ROLOVR	26
#define	ROLOVR	26
#define	param_MF	27
#define	MF	27
#define	param_SF	28
#define	SF	28
#define	param_RAWPV	29
#define	RAWPV	29
#define	param_EXTZNE	81
#define	EXTZNE	81
#define	param_LSTACD	82
#define	LSTACD	82
#define	param_LSTACS	83
#define	LSTACS	83
#define	param_LSTACT	84
#define	LSTACT	84
#define	param_TIMEATT	324
#define	param_CREDENTIAL	325
#define	param_RelatedEquipment	133
#define	param_EquipProperties	717
#define	param_EquipDisplayElements	718
#define	param_EquipDisplayElementBindings	719
#define	param_EquipAggrDisplayElements	720
#define	param_EquipAggrDisplayElementBindings	721
#define	param_EquipAggregateTables	722
#define	param_FlexStationAssignment	190
#define	param_FlexStationPermission	191
#define	param_ConsoleStationAssignment	192
#define	param_ConsoleStationPermission	193
#define	param_ConsoleAssignment	194
#define	param_ConsolePermission	195
#define	param_OperatorAssignment	196
#define	param_OperatorPermission	197
#define	param_ProfileListAssignment	198
#define	param_ProfileListPermission	199
#define	param_FlexStationPropagatedAssignment	214
#define	param_FlexStationPropagatedPermission	215
#define	param_ConsoleStationPropagatedAssignment	216
#define	param_ConsoleStationPropagatedPermission	217
#define	param_ConsolePropagatedAssignment	218
#define	param_ConsolePropagatedPermission	219
#define	param_OperatorPropagatedAssignment	220
#define	param_OperatorPropagatedPermission	221
#define	param_ProfileListPropagatedAssignment	222
#define	param_ProfileListPropagatedPermission	223
#define	param_FlexStationAssignmentMatchesDescendents	224
#define	param_FlexStationPermissionMatchesDescendents	225
#define	param_ConsoleStationAssignmentMatchesDescendents	226
#define	param_ConsoleStationPermissionMatchesDescendents	227
#define	param_ConsoleAssignmentMatchesDescendents	228
#define	param_ConsolePermissionMatchesDescendents	229
#define	param_OperatorAssignmentMatchesDescendents	230
#define	param_OperatorPermissionMatchesDescendents	231
#define	param_ProfileListAssignmentMatchesDescendents	232
#define	param_ProfileListPermissionMatchesDescendents	233
#define	param_AlarmPropagatedDisabled	235
#define	param_AlarmDisabledMatchesDescendents	236
#define	param_FlexStationPermAllowWrite	239
#define	param_FlexStationPermAllowPropagatedWrite	240
#define	param_ConsoleStationPermAllowWrite	241
#define	param_ConsoleStationPermAllowPropagatedWrite	242
#define	param_ConsolePermAllowWrite	243
#define	param_ConsolePermAllowPropagatedWrite	244
#define	param_OperatorPermAllowWrite	245
#define	param_OperatorPermAllowPropagatedWrite	246
#define	param_ProfileListPermAllowWrite	247
#define	param_ProfileListPermAllowPropagatedWrite	248
#define	param_StationEffectiveSecurityPermissions	290
#define	param_SignaturePropagatedDisabled	463
#define	param_SignatureDisabledMatchesDescendents	464
#define	param_ConsoleAlarmDisabled	855
#define	param_ConsoleAlarmPropagatedDisabled	856
#define	param_ConsoleAlarmDisabledMatchesDescendents	857
#define	param_ConsoleAlarmSynch	858
#define	param_AssignedConsoleAlarmDisabledDescendants	859
#define	param_ConsoleAlarmSynchText	861
#define	param_AssociatedAssetTagName	209
#define	param_AssociatedAssetFullItemName	210
#define	param_DashboardDisplay	846
#define	param_Status	384
#define	param_PrimaryStatus	414
#define	param_BackupStatus	415
#define	param_BackupSyncStatus	416
#define	param_Link1Status	417
#define	param_Link2Status	418
#define	param_LastSyncTime	419
#define	param_LastLostSyncTime	420
#define	param_LastSyncDate	421
#define	param_LastLostSyncDate	422
#define	param_DataStatus	425
#define	param_NotificationStatus	426
#define	param_DSALink0State	433
#define	param_DSALink1State	434
#define	param_DSALink2State	435
#define	param_DSALink3State	436
#define	param_DSALink0FullName	437
#define	param_DSALink1FullName	438
#define	param_DSALink2FullName	439
#define	param_DSALink3FullName	440
#define	param_DSACurrentPrimaryServer	441
#define	param_IsRedundantPair	465
#define	param_CmsSyncStatus	479
#define	param_CmsDSAEnabled	480
#define	param_Release	796
#define	param_FailPriority	92
#define	FailPriority	92
#define	param_MargPriority	93
#define	MargPriority	93
#define	param_DiagPriority	94
#define	DiagPriority	94
#define	param_FailSubPriority	102
#define	FailSubPriority	102
#define	param_MargSubPriority	103
#define	MargSubPriority	103
#define	param_DiagSubPriority	104
#define	DiagSubPriority	104
#define	param_LnkATotalRequests	385
#define	param_LnkBTotalRequests	386
#define	param_LnkATotalErrors	387
#define	param_LnkBTotalErrors	388
#define	param_LnkAPercentErrors	389
#define	param_LnkBPercentErrors	390
#define	param_BarFailLimit	391
#define	param_BarMarginalLimit	392
#define	param_LnkABarCount	393
#define	param_LnkBBarCount	394
#define	param_LinkAEnabled	442
#define	param_LinkBEnabled	443
#define	param_LinkAImplemented	444
#define	param_LinkBImplemented	445
#define	param_ConnectionType	446
#define	param_LinkAStatus	448
#define	param_LinkBStatus	449
#define	param_ChnType	478
#define	param_StatsAvgPeriod	659
#define	param_TaskBusy	660
#define	param_DAQLength	661
#define	param_CNQLength	662
#define	param_Utilization	663
#define	param_UtilizationLinkA	664
#define	param_UtilizationLinkB	665
#define	param_UtilizationAvg	666
#define	param_UtilizationAvgLinkA	667
#define	param_UtilizationAvgLinkB	668
#define	param_ResponseTime	669
#define	param_ResponseTimeLinkA	670
#define	param_ResponseTimeLinkB	671
#define	param_ResponseTimeMin	672
#define	param_ResponseTimeMinLinkA	673
#define	param_ResponseTimeMinLinkB	674
#define	param_ResponseTimeMax	675
#define	param_ResponseTimeMaxLinkA	676
#define	param_ResponseTimeMaxLinkB	677
#define	param_ResponseTimeAvg	678
#define	param_ResponseTimeAvgLinkA	679
#define	param_ResponseTimeAvgLinkB	680
#define	param_RequestsPerSec	681
#define	param_RequestsPerSecLinkA	682
#define	param_RequestsPerSecLinkB	683
#define	param_RequestsPerSecMin	684
#define	param_RequestsPerSecMinLinkA	685
#define	param_RequestsPerSecMinLinkB	686
#define	param_RequestsPerSecMax	687
#define	param_RequestsPerSecMaxLinkA	688
#define	param_RequestsPerSecMaxLinkB	689
#define	param_RequestsPerSecAvg	690
#define	param_RequestsPerSecAvgLinkA	691
#define	param_RequestsPerSecAvgLinkB	692
#define	param_BytesPerSecRead	693
#define	param_BytesPerSecReadLinkA	694
#define	param_BytesPerSecReadLinkB	695
#define	param_BytesPerSecReadMin	696
#define	param_BytesPerSecReadMinLinkA	697
#define	param_BytesPerSecReadMinLinkB	698
#define	param_BytesPerSecReadMax	699
#define	param_BytesPerSecReadMaxLinkA	700
#define	param_BytesPerSecReadMaxLinkB	701
#define	param_BytesPerSecReadAvg	702
#define	param_BytesPerSecReadAvgLinkA	703
#define	param_BytesPerSecReadAvgLinkB	704
#define	param_BytesPerSecWritten	705
#define	param_BytesPerSecWrittenLinkA	706
#define	param_BytesPerSecWrittenLinkB	707
#define	param_BytesPerSecWrittenMin	708
#define	param_BytesPerSecWrittenMinLinkA	709
#define	param_BytesPerSecWrittenMinLinkB	710
#define	param_BytesPerSecWrittenMax	711
#define	param_BytesPerSecWrittenMaxLinkA	712
#define	param_BytesPerSecWrittenMaxLinkB	713
#define	param_BytesPerSecWrittenAvg	714
#define	param_BytesPerSecWrittenAvgLinkA	715
#define	param_BytesPerSecWrittenAvgLinkB	716
#define	param_ConfiguredPacketCount	737
#define	param_ConfiguredPacketRate	738
#define	param_PacketCount	739
#define	param_PacketRate	740
#define	param_EFMLogRequestRate	741
#define	param_LnkBKeyLen	742
#define	param_LnkBAlgo	743
#define	param_LnkBEncLED	744
#define	param_LnkAEncLED	745
#define	param_LnkAKeyLen	746
#define	param_LnkAAlgo	747
#define	param_LnkBShow	750
#define	param_ChannelNumber	752
#define	param_OverloadStatus	753
#define	param_SimulationMode	754
#define	param_UpldPerm	782
#define	param_DwnldPerm	783
#define	param_ShwAlarms	784
#define	param_TORefresh	785
#define	param_Hiway	786
#define	param_PIUorDHP	787
#define	param_HiwaySwitch	788
#define	param_ChnNumber	481
#define	param_DynamicScanningDisabled	733
#define	param_DynamicScanningPeriod	734
#define	param_FastScan	735
#define	param_OnceOffScan	736
#define	param_Integration	751
#define	param_CLinkAddress	756
#define	param_FS90AMCSubdevice1	853
#define	param_FS90AMCSubdevice2	854
#define	param_ControllerType	757
#define	param_ControllerId	758
#define	param_Buff3LateTime	759
#define	param_Buff3LateDate	760
#define	param_Buff3EarlTime	761
#define	param_Buff3EarlDate	762
#define	param_Buff2LateTime	763
#define	param_Buff2LateDate	764
#define	param_Buff2EarlTime	765
#define	param_Buff2EarlDate	766
#define	param_Buff1LateTime	767
#define	param_Buff1LateDate	768
#define	param_Buff1EarlTime	769
#define	param_Buff1EarlDate	770
#define	param_Buff1Conf	771
#define	param_Buff2Conf	772
#define	param_Buff3Conf	773
#define	param_histEnable	774
#define	param_ClLib	775
#define	param_ControllerNumber	776
#define	param_DualCh	778
#define	param_Exc5000Strat	780
#define	param_ChType	781
#define	param_ErrorCode	797
#define	param_Checksum_Rtu	860
#define	param_Enabled	395
#define	param_FontSize	396
#define	param_DetailStatus	431
#define	param_DataConnectionStatus	423
#define	param_NotificationConnectionStatus	424
#define	param_DataServerState	427
#define	param_NotificationServerState	428
#define	param_DataLink0State	451
#define	param_DataLink1State	452
#define	param_DataLink0Suffix	453
#define	param_DataLink1Suffix	454
#define	param_NotificationLink0State	455
#define	param_DataNetworkBaseName	456
#define	param_NotificationNetworkBaseName	457
#define	param_NotificationEnabled	458
#define	param_Type	459
#define	param_TPNSystemStatus	489
#define	param_TPNConfigured	491
#define	param_StationType	397
#define	param_EnableLowAlarms	398
#define	param_EnableHighAlarms	399
#define	param_EnableUrgentAlarms	400
#define	param_EnableFailAlarms	401
#define	param_EnableSignOffAlarms	402
#define	param_IPAddress	403
#define	param_IPName	404
#define	param_Operator	405
#define	param_NetworkName	430
#define	param_StationStatus	447
#define	param_DatacastStatus	408
#define	param_FileReplicationStatus	409
#define	param_PointReplicationStatus	410
#define	param_FileRedirectionStatus	411
#define	param_PointRedirectionStatus	412
#define	param_NotificationRedirectionStatus	413
#define	param_NodeStatus	429
#define	param_CDACommsDataConnection	460
#define	param_CDACommsNotificationConnection	461
#define	param_TPNConsoleStatus	490
#define	param_Console	865
#define	param_NumberOfStations	406
#define	param_OperatorSignOn	407
#define	param_ConsoleStatus	450
#define	param_TotalConsoleAlarmDisabled	862
#define	param_TotalConsoleAlarmDisabledNotSynced	863
#define	param_TotalAlarmDisabled	864
#define	param_ResetStatistics	493
#define	param_ManualScan	494
#define	param_ManualExport	495
#define	param_ManualExportFrom	496
#define	param_MeterEnabled	395
#define	param_EFMDailyRegister	723
#define	param_EFMDailyPointerLatest	724
#define	param_EFMDailyRollover	725
#define	param_EFMDailyLogLength	789
#define	param_EFMDailyFieldCount	790
#define	param_EFMIntervalRegister	726
#define	param_EFMIntervalPointerLatest	727
#define	param_EFMIntervalRollover	728
#define	param_EFMIntervalLogLength	791
#define	param_EFMIntervalFieldCount	792
#define	param_EFMAuditRegister	729
#define	param_EFMAuditPointerLatest	730
#define	param_EFMAuditRollover	731
#define	param_EFMAuditAckRegister	732
#define	param_EFMAuditLogLength	793
#define	param_EFMAuditFieldCount	794
#define	param_EFMUltrasonicRegister	798
#define	param_EFMUltrasonicPointerLatest	799
#define	param_EFMUltrasonicRollover	800
#define	param_EFMUltrasonicLogLength	801
#define	param_EFMUltrasonicFieldCount	802
#define	param_EFMGasQualityRegister	803
#define	param_EFMGasQualityPointerLatest	804
#define	param_EFMGasQualityRollover	805
#define	param_EFMGasQualityLogLength	806
#define	param_EFMGasQualityFieldCount	807
#define	param_EFMCompositionRegister	808
#define	param_EFMCompositionPointerLatest	809
#define	param_EFMCompositionRollover	810
#define	param_EFMCompositionLogLength	811
#define	param_EFMCompositionFieldCount	812
#define	param_EFMConfigRecordRegister	813
#define	param_EFMConfigRecordPointerLatest	814
#define	param_EFMConfigRecordRollover	815
#define	param_EFMConfigRecordLogLength	816
#define	param_EFMConfigRecordFieldCount	817
#define	param_EFMLiquidBatchRegister	835
#define	param_EFMLiquidBatchPointerLatest	836
#define	param_EFMLiquidBatchRollover	837
#define	param_EFMLiquidBatchLogLength	838
#define	param_EFMLiquidBatchFieldCount	839
#define	param_EFMLiquidBatchParams	851
#define	param_EFMAudit2Register	840
#define	param_EFMAudit2PointerLatest	841
#define	param_EFMAudit2Rollover	842
#define	param_EFMAudit2AckRegister	843
#define	param_EFMAudit2LogLength	844
#define	param_EFMAudit2FieldCount	845
#define	param_ParametersInSubscription	818
#define	param_ParametersInFastSubscription	819
#define	param_QueueAvailable	659
#define	param_MessagesPerSecond	660
#define	param_SynchStatus	661
#define	param_MsgNo	662
#define	param_AckNo	663
#define	param_LinkStatusA	448
#define	param_LinkStatusB	449
#define	param_LinkStatusA0	451
#define	param_LinkStatusA1	452
#define	param_LinkStatusB0	453
#define	param_LinkStatusB1	454
#define	param_SynchStatusA	455
#define	param_SynchStatusB	456
#define	param_CPUSTSflagsA	659
#define	param_CPUSTSflagsB	660
#define	param_LNKSTSflagsA	661
#define	param_LNKSTSflagsB	662
#define	param_MessageNumberA	663
#define	param_MessageNumberB	664
#define	param_LastMessageNumberA	665
#define	param_LastMessageNumberB	666
#define	param_AckMessageNumberA	667
#define	param_AckMessageNumberB	668
#define	param_AckRedunMessageNumberA	669
#define	param_AckRedunMessageNumberB	670
#define	param_KeepAlivePeriodA	671
#define	param_KeepAlivePeriodB	672
#define	param_LinkInUseA	673
#define	param_LinkInUseB	674
#define	param_LinkTypeA	675
#define	param_LinkTypeB	676
#define	param_LinkTimeoutA	677
#define	param_LinkTimeoutB	678
#define	param_OPMflagsA	679
#define	param_OPMflagsB	680
#define	param_DBReleaseA	681
#define	param_DBReleaseB	682
#define	param_DBReleaseAdjA	683
#define	param_DBReleaseAdjB	684
#define	param_ProtocolVersionA	685
#define	param_ProtocolVersionB	686
#define	param_LastSyncDateA	687
#define	param_LastSyncDateB	688
#define	param_LastSyncTimeA	689
#define	param_LastSyncTimeB	690
#define	param_LostSyncDateA	691
#define	param_LostSyncDateB	692
#define	param_LostSyncTimeA	693
#define	param_LostSyncTimeB	694
#define	param_LastSyncFromBCCA	695
#define	param_LastSyncFromBCCB	696
#define	param_LastSyncFromBorAA	697
#define	param_LastSyncFromBorAB	698
#define	param_QueueUsedA	699
#define	param_QueueUsedB	700
#define	param_QueueMaxA	701
#define	param_QueueMaxB	702
#define	param_DataTransferRateA	703
#define	param_DataTransferRateB	704
#define	param_MessageTransferRateA	705
#define	param_MessageTransferRateB	706
#define	param_ActiveLocationA	707
#define	param_ActiveLocationB	708
#define	param_SynchProgressA	709
#define	param_SynchProgressB	710
#define	param_BytesSentA	711
#define	param_BytesSentB	712
#define	param_MessagesSentA	713
#define	param_MessagesSentB	714
#define	param_LastSyncAttemptDateA	715
#define	param_LastSyncAttemptDateB	716
#define	param_LastSyncAttemptTimeA	717
#define	param_LastSyncAttemptTimeB	718
#define	param_NameA	719
#define	param_NameB	730
#define	param_IsRedundant	866
#define	param_QSTABL	112
#define	param_CEENUM	115
#define	param_ActivityCreationEnabled	483
#define	param_ActivityType	484
#define	param_PointDetailDisplayError	202
#define	param_GroupDetailDisplayError	208
#define	param_FullPublicName	486
#define	param_RemotePromptOnEnable	795
#define	param_ReasonSetNumber	203
#define	param_PrimarySignatureMeaning	204
#define	param_SecondarySignerSecLevel	205
#define	param_SecondarySignatureMeaning	206
#define	param_ServicesAvailable	207
#define	param_AlarmPriority1	468
#define	param_AlarmPriority2	469
#define	param_AlarmPriority3	470
#define	param_AlarmPriority4	471
#define	param_AlarmPriority5	472
#define	param_AlarmSubPriority1	473
#define	param_AlarmSubPriority2	474
#define	param_AlarmSubPriority3	475
#define	param_AlarmSubPriority4	476
#define	param_AlarmSubPriority5	477
#define	param_PointServerTypeNo	492

/*	Parameter subtypes */

#define	SP_NUMB	1
#define	SP_ENUM	2
#define	SP_CHAR	3

/*	Parameter subtype numbers */

#define	subparam_Value	1
#define	subparam_EULO	2
#define	subparam_EUHI	3
#define	subparam_FieldValue	4
#define	subparam_Source	5
#define	subparam_Destination	6
#define	subparam_Period	7
#define	subparam_Controller	8
#define	subparam_Bias	9
#define	subparam_Scale	10
#define	subparam_Units	11
#define	subparam_DFTDEADBAND	12
#define	subparam_ALMDEADBAND	13
#define	subparam_CNTDEADBAND	14
#define	subparam_BiasScaleEnable	15
#define	subparam_Clamp	16
#define	subparam_ALMSTS	31
#define	subparam_AlarmPriority	32
#define	subparam_AlarmSubPriority	33
#define	subparam_DynamicScanningDisabled	35
#define	subparam_Reverse	36
#define	subparam_Manual	37
#define	subparam_LastScannedTime	38
#define	subparam_LastProcessedTime	39
#define	subparam_PVALG	40
#define	subparam_PVBLK	41
#define	subparam_ACALG	42
#define	subparam_ACBLK	43
#define	subparam_FieldStatus	45
#define	subparam_ValueStatus	46
#define	subparam_FieldQuality	47
#define	subparam_ValueQuality	48
#define	subparam_AssociatedParameter	49
#define	subparam_AlarmExternalChange	50
#define	subparam_ALRMSG	51
#define	subparam_RateLimit	52
#define	subparam_LoLimit	53
#define	subparam_HiLimit	54
#define	subparam_LoLoLimit	55
#define	subparam_HiHiLimit	56
#define	subparam_XtLoLimit	57
#define	subparam_XtHiLimit	58
#define	subparam_RateOnDelay	60
#define	subparam_LoOnDelay	61
#define	subparam_HiOnDelay	62
#define	subparam_LoLoOnDelay	63
#define	subparam_HiHiOnDelay	64
#define	subparam_XtLoOnDelay	65
#define	subparam_XtHiOnDelay	66
#define	subparam_RateOffDelay	68
#define	subparam_LoOffDelay	69
#define	subparam_HiOffDelay	70
#define	subparam_LoLoOffDelay	71
#define	subparam_HiHiOffDelay	72
#define	subparam_XtLoOffDelay	73
#define	subparam_XtHiOffDelay	74
#define	subparam_RatePriority	76
#define	subparam_LoPriority	77
#define	subparam_HiPriority	78
#define	subparam_LoLoPriority	79
#define	subparam_HiHiPriority	80
#define	subparam_XtLoPriority	81
#define	subparam_XtHiPriority	82
#define	subparam_RateSubPriority	84
#define	subparam_LoSubPriority	85
#define	subparam_HiSubPriority	86
#define	subparam_LoLoSubPriority	87
#define	subparam_HiHiSubPriority	88
#define	subparam_XtLoSubPriority	89
#define	subparam_XtHiSubPriority	90
#define	subparam_RateEnabled	92
#define	subparam_LoEnabled	93
#define	subparam_HiEnabled	94
#define	subparam_LoLoEnabled	95
#define	subparam_HiHiEnabled	96
#define	subparam_XtLoEnabled	97
#define	subparam_XtHiEnabled	98
#define	subparam_RateActive	100
#define	subparam_LoActive	101
#define	subparam_HiActive	102
#define	subparam_LoLoActive	103
#define	subparam_HiHiActive	104
#define	subparam_XtLoActive	105
#define	subparam_XtHiActive	106
#define	subparam_InRateOnDelay	108
#define	subparam_InLoOnDelay	109
#define	subparam_InHiOnDelay	110
#define	subparam_InLoLoOnDelay	111
#define	subparam_InHiHiOnDelay	112
#define	subparam_InXtLoOnDelay	113
#define	subparam_InXtHiOnDelay	114
#define	subparam_InRateOffDelay	116
#define	subparam_InLoOffDelay	117
#define	subparam_InHiOffDelay	118
#define	subparam_InLoLoOffDelay	119
#define	subparam_InHiHiOffDelay	120
#define	subparam_InXtLoOffDelay	121
#define	subparam_InXtHiOffDelay	122
#define	subparam_Units0	9
#define	subparam_Units1	10
#define	subparam_Units2	11
#define	subparam_Units3	12
#define	subparam_Units4	13
#define	subparam_Units5	14
#define	subparam_Units6	15
#define	subparam_Units7	16
#define	subparam_TargetForState0	17
#define	subparam_TargetForState1	18
#define	subparam_TargetForState2	19
#define	subparam_TargetForState3	20
#define	subparam_TargetForState4	21
#define	subparam_TargetForState5	22
#define	subparam_TargetForState6	23
#define	subparam_TargetForState7	24
#define	subparam_ReverseMask	25
#define	subparam_State0OnDelay	60
#define	subparam_State1OnDelay	61
#define	subparam_State2OnDelay	62
#define	subparam_State3OnDelay	63
#define	subparam_State4OnDelay	64
#define	subparam_State5OnDelay	65
#define	subparam_State6OnDelay	66
#define	subparam_State7OnDelay	67
#define	subparam_State0OffDelay	68
#define	subparam_State1OffDelay	69
#define	subparam_State2OffDelay	70
#define	subparam_State3OffDelay	71
#define	subparam_State4OffDelay	72
#define	subparam_State5OffDelay	73
#define	subparam_State6OffDelay	74
#define	subparam_State7OffDelay	75
#define	subparam_State0Priority	76
#define	subparam_State1Priority	77
#define	subparam_State2Priority	78
#define	subparam_State3Priority	79
#define	subparam_State4Priority	80
#define	subparam_State5Priority	81
#define	subparam_State6Priority	82
#define	subparam_State7Priority	83
#define	subparam_State0SubPriority	84
#define	subparam_State1SubPriority	85
#define	subparam_State2SubPriority	86
#define	subparam_State3SubPriority	87
#define	subparam_State4SubPriority	88
#define	subparam_State5SubPriority	89
#define	subparam_State6SubPriority	90
#define	subparam_State7SubPriority	91
#define	subparam_State0AlarmEnabled	92
#define	subparam_State1AlarmEnabled	93
#define	subparam_State2AlarmEnabled	94
#define	subparam_State3AlarmEnabled	95
#define	subparam_State4AlarmEnabled	96
#define	subparam_State5AlarmEnabled	97
#define	subparam_State6AlarmEnabled	98
#define	subparam_State7AlarmEnabled	99
#define	subparam_State0AlmarmActive	100
#define	subparam_State1AlmarmActive	101
#define	subparam_State2AlmarmActive	102
#define	subparam_State3AlmarmActive	103
#define	subparam_State4AlmarmActive	104
#define	subparam_State5AlmarmActive	105
#define	subparam_State6AlmarmActive	106
#define	subparam_State7AlmarmActive	107
#define	subparam_InState0OnDelay	108
#define	subparam_InState1OnDelay	109
#define	subparam_InState2OnDelay	110
#define	subparam_InState3OnDelay	111
#define	subparam_InState4OnDelay	112
#define	subparam_InState5OnDelay	113
#define	subparam_InState6OnDelay	114
#define	subparam_InState7OnDelay	115
#define	subparam_InState0OffDelay	116
#define	subparam_InState1OffDelay	117
#define	subparam_InState2OffDelay	118
#define	subparam_InState3OffDelay	119
#define	subparam_InState4OffDelay	120
#define	subparam_InState5OffDelay	121
#define	subparam_InState6OffDelay	122
#define	subparam_InState7OffDelay	123

#endif	
